### ISSUE TITLE
Position 4 

### ISSUE THREAD

**Issue by steepleian** [weather34/Meteobridge-Weather34-Template#11]
Have noticed that when advisory.php selected for position 4 that text and images are mis-positioned within the box. This happens with both dark and light themes.
![screenshot 2019-03-05 at 08 10 51](https://user-images.githubusercontent.com/18438654/53791357-20e72280-3f21-11e9-919f-d59013b3f254.png)

**Comment by weather34** [comment]
are you using a recent meteobridge version ?? or is this a weewx/cumulus version because in meteobridge version current advisory php  rain alert does not have two alert icons ..

//weather34 darksky alerts rain,snow  
  else if ($darkskydayIcon=='snow')
  {echo '<spanelightning>'.$snowalert.'<alertvalue> Expect <blue>Snow Showers</blue> This Week <alertadvisory>'.$newalertcold.'</alertadvisory>
   </spanelightning></div></div></div>';}   
    else if ($darkskydayIcon=='rain')
  {echo '<spanelightning><alertvalue> Expect <blue>Rain Showers</blue> This Week <alertadvisory>'.$newalertcold.'</alertadvisory>
   </spanelightning></div></div></div>';}

**Comment by weather34** [comment]
i just checked i dont see two icons outputs in rain alert

**Comment by weather34** [comment]
however updated file to wu forecast values as well as darksky..thanks for the reminder

**Comment by weather34** [comment]
![ian](https://user-images.githubusercontent.com/20555738/53793193-62d29180-3f3e-11e9-9756-b42354f510ff.png)

**Comment by steepleian** [comment]
Here is the link. https://claydonsweather.org.uk/Meteobridge-Weather34-Template-master/

Its the master with my darksky key and some UK settings entered via easyweathersetup. I am using a dummy MB realtime.txt file to the MB standard.

**Comment by weather34** [comment]
not sure is it using the latest advisory.php ?? you have multiple errors appearing if it is using dummy MBrealtimeupload.txt why is wind data updating ??...you have numerous nulls ? 

try using the latest advisory.php ? 
![ian](https://user-images.githubusercontent.com/20555738/53794958-ffe2f980-3f41-11e9-9267-f53bc7350d03.png)

**Comment by steepleian** [comment]
The other errors are OK its because only linked to demodata/MBrealtimeupload.txt at the moment, You must have caught me when I was checking with some live data for a moment or two. The interesting think is if I enter some higher temperatures in the demo file to trigger fire risk in panel 4 all is aligned ok.

**Comment by steepleian** [comment]
Null on barometer - indoor sensor broken at moment - awaiting replacement from Germany

**Comment by weather34** [comment]
ok you need to replace that advisory.php it will fix that .. and go through some of the recent file updates ..so are you now using meteobridge as a device hub..?

**Comment by steepleian** [comment]
Nope, I have taken Meteohub.api (as in your livedata) and recreated all the variables with WeeWX, and it works! 
The plan going forwards is if WeeWX are happy to just use WU charts and no Almanac, I will recommend either Ken or Wim (as they can both be used for WeeWX as well).

I will continue to support those users who want to go the whole WeeWX hog and use their WeeWX database for charts and almanac. I have not found anything yet that WeeWX cannot mimic, so in that respect WeeWX and Meteobridge are very alike - they just differ in the way you get the data out, but the data is the same.

All I have to do is to drop in my own version of livedata. This has the added big positive for me that the full Monty WeeWX version is a s close as visually and functionally possible to the MB master.

**Comment by steepleian** [comment]
Sorry Brian, just read your readme update. I should have let you know what I was up to.

**Comment by weather34** [comment]
ok ian unless you take the current master you may run into some alignment issues ..good luck and please leave the footer credit intact its not a lot to ask for but seems troublesome for some ..a lot of work goes into this version and many users collaborate and we all get the benefit in the end ..being ethical is not

**Comment by steepleian** [comment]
Thanks Brian and yes I always keep a hard link in the footer.
