### ISSUE TITLE
DarkSky Forecast Summary / Hourly Forecast Anomaly

### ISSUE THREAD

**Issue by chrismaltese** [weather34/Meteobridge-Weather34-Template#2]
In the attached, you'll notice abnormally high values in all fields of the forecast frame.  I checked my DarkSky data with an API query and the values were correct.

![greenshot 2019-02-20 10 03 39](https://user-images.githubusercontent.com/47764765/53100982-d57f4e00-34f6-11e9-9393-24a31655fb02.png)

**Comment by weather34** [comment]
arggh so sorry fixed outlookds.php and forecastdshour.php files via https://github.com/weather34/Meteobridge-Weather34-Template


I hand over the less mistakes going forward…brian

**Comment by chrismaltese** [comment]
No worries, bud.  I'll add the new files.

--Chris

**Comment by chrismaltese** [comment]
Thanks Brian, no worries :)

I'm new to Github.  Is there a way to download only the files that I need?

--Chris

**Comment by weather34** [comment]
im new as well but if you are using the master you can track by the time ago the file was updated . and just replace the files . unless you see a change to easyweathersetup the settings1.php never has to be changed or updated .

**Comment by chrismaltese** [comment]
Good guidance.  Thank you.

**Comment by steepleian** [comment]
Probably not the right way but click on the file required to open it. Click raw button then you can cut and paste from your browser to an open empty file on your computer.

**Comment by chrismaltese** [comment]
Was looking at that and thinking same.  Another thought.  If I have the ability to see barometric pressure in millibars - and it is selected in settings, why does it always show as in/hg?  Just curious.

**Comment by weather34** [comment]
been asked before but mixing metrics and non metrics and so on requires a lot of testing not only in modules but charts .. at this stage i wont look into but lets see what happens in may..brian

**Comment by chrismaltese** [comment]
Sounds good Brian.  That would be great but understand the amount of work.

**Comment by lightmaster** [comment]
Start another issue about the pressure units and I'll look into it later on today. I use mixed units too and had to modify the code initially to get it to work.
