### ISSUE TITLE
Add ability to use different pressure readings

### ISSUE THREAD

**Issue by chrismaltese** [weather34/Meteobridge-Weather34-Template#3]
Suggesting the implementation of various pressure readings in imperial or metric formats.  That is, if in US imperial, have barometric pressure display in millibars instead of in/hg.

**Comment by lightmaster** [comment]
I just copied the barometer.php file to my server from a fresh clone of the repo, and it shows mb just fine for me. Check your `settings1.php` file and see what unit is listed for `$pressureunit`

![image](https://i.imgur.com/dyPpRSo.jpg)

**Comment by chrismaltese** [comment]
Thanks for the info.  This may very well be a self-inflicted wound on my part as settings1.php reveals $pressureunit  = "mb";

On a daily basis, I view my data using a program called "Fluid" which allows you to create a container for any url and make it run like an app without a browser.  For whatever reason, I cannot see pressure in mb.  On Mac and iPad I see millibars being displayed.  

Fluid:
![greenshot 2019-02-21 12 38 19](https://user-images.githubusercontent.com/47764765/53189500-a5f34300-35d5-11e9-90a7-9e97fb43a10e.png)

I'll try and rebuild the app and se what happens.  Sorry for the wheel spin.

--Chris
