### ISSUE TITLE
Rain Graph with high rain rate unreadable

### ISSUE THREAD

**Issue by dive76** [weather34/Meteobridge-Weather34-Template#4]
Rain graph becomes unreadable if having high rain rates >30mm/hour which is very common in Singapore. Propose to change the graph into a 2 axis graph which would solve the issue.

**Comment by weather34** [comment]
updated in folder mbcharts the raintoday.php now has 2nd Y axis for rain rate 

![rrate](https://user-images.githubusercontent.com/20555738/53140888-34989d80-359f-11e9-9e17-495274ba604f.png)
