### ISSUE TITLE
Bad conversion of barometric units reintroduced 

### ISSUE THREAD

**Issue by lightmaster** [weather34/Meteobridge-Weather34-Template#8]
In ff828802e87dde6552236978d9c89fa62f559883, lines 7-14 of barometer.php, looks like some old code worked its way back in, incorrectly converting the pressure based on temp units chosen and not barometric units chosen.

[![C4-F3-D0-F1-7644-4-B58-99-C4-4717-D5-EC1458.png](https://i.postimg.cc/7ZqYXSWN/C4-F3-D0-F1-7644-4-B58-99-C4-4717-D5-EC1458.png)](https://postimg.cc/tYmj4ny1)

**Comment by weather34** [comment]
reverted back to original
